### ISSUE TITLE
Unable to start the UI with NPM error

### ISSUE THREAD

**Issue by bryanleekw** [speedd-project/speedd#70]
Unable to start the UI with NPM error
when I tried to run ui docker, and found the following error to install npm, any ideas why?

ui_1          | SPEEDD UI - starting
ui_1          | Starting sshd
ui_1          | Installing required node modules
ui_1          | /opt/start-ui.sh: 7: cd: can't cd to /opt/speedd/speedd_ui_tm_version2
ui_1          | npm info it worked if it ends with ok
ui_1          | npm info using npm@2.14.12
ui_1          | npm info using node@v4.2.6
ui_1          | npm ERR! install Couldn't read dependencies
ui_1          | npm ERR! Linux 4.13.0-21-generic
ui_1          | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
ui_1          | npm ERR! node v4.2.6
ui_1          | npm ERR! npm  v2.14.12
ui_1          | npm ERR! path /package.json
ui_1          | npm ERR! code ENOPACKAGEJSON
ui_1          | npm ERR! errno -2
ui_1          | npm ERR! syscall open
ui_1          | 
ui_1          | npm ERR! package.json ENOENT: no such file or directory, open '/package.json'
ui_1          | npm ERR! package.json This is most likely not a problem with npm itself.
ui_1          | npm ERR! package.json npm can't find a package.json file in your current directory.
ui_1          | 
ui_1          | npm ERR! Please include the following file with any support request:
ui_1          | npm ERR!     /npm-debug.log
ui_1          | Sleep 1m till kafka is up and topics initialized

**Comment by natan-morar** [comment]
HI,

sorry to get back to you only now.

line 4 says:

ui_1 | /opt/start-ui.sh: 7: cd: can't cd to /opt/speedd/speedd_ui_tm_version2

maybe folder does not exists, or incorrect path

Best wishes,
Natan

On 24 Dec 2017, at 01:17, notifications@github.com<mailto:notifications@github.com> wrote:


Unable to start the UI with NPM error
when I tried to run ui docker, and found the following error to install npm, any ideas why?

ui_1 | SPEEDD UI - starting
ui_1 | Starting sshd
ui_1 | Installing required node modules
ui_1 | /opt/start-ui.sh: 7: cd: can't cd to /opt/speedd/speedd_ui_tm_version2
ui_1 | npm info it worked if it ends with ok
ui_1 | npm info using npm@2.14.12
ui_1 | npm info using node@v4.2.6
ui_1 | npm ERR! install Couldn't read dependencies
ui_1 | npm ERR! Linux 4.13.0-21-generic
ui_1 | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
ui_1 | npm ERR! node v4.2.6
ui_1 | npm ERR! npm v2.14.12
ui_1 | npm ERR! path /package.json
ui_1 | npm ERR! code ENOPACKAGEJSON
ui_1 | npm ERR! errno -2
ui_1 | npm ERR! syscall open
ui_1 |
ui_1 | npm ERR! package.json ENOENT: no such file or directory, open '/package.json'
ui_1 | npm ERR! package.json This is most likely not a problem with npm itself.
ui_1 | npm ERR! package.json npm can't find a package.json file in your current directory.
ui_1 |
ui_1 | npm ERR! Please include the following file with any support request:
ui_1 | npm ERR! /npm-debug.log
ui_1 | Sleep 1m till kafka is up and topics initialized

**Comment by bryanleekw** [comment]
issue has been solved, since I have not specified correct path on yml file.
